# Generated by Django 5.2.5 on 2025-12-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeide', '0002_codefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
