# Generated by Django 5.2.5 on 2026-02-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeide', '0003_codesubmission_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(choices=[('javascript', 'javascript'), ('html', 'html'), ('CSS', 'CSS'), ('python', 'python'), ('java', 'java')], default='html', max_length=64),
        ),
    ]
