# Generated by Django 5.2.5 on 2026-02-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeide', '0004_alter_codesnippet_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('javascript', 'javascript'), ('html', 'html'), ('CSS', 'CSS'), ('python', 'python'), ('java', 'java')], default='html', max_length=64),
        ),
    ]
