# Generated by Django 5.2.5 on 2026-02-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeide', '0005_alter_codesubmission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(choices=[('javascript', 'javascript'), ('html', 'html'), ('css', 'css'), ('python', 'python'), ('java', 'java')], default='html', max_length=64),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('javascript', 'javascript'), ('html', 'html'), ('css', 'css'), ('python', 'python'), ('java', 'java')], default='html', max_length=64),
        ),
    ]
