# Generated by Django 5.2.5 on 2026-05-01 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_alter_studentprofile_admission_no'),
        ('codeide', '0006_alter_codesnippet_language_and_more'),
        ('learning', '0025_course_parent_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='codeide.folder')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='academics.studentprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='codefile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='codeide.folder'),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snippets', to='codeide.folder'),
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['student', 'folder'], name='codeide_cod_student_5c2c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='codesnippet',
            index=models.Index(fields=['student', 'folder'], name='codeide_cod_student_831212_idx'),
        ),
        migrations.AddIndex(
            model_name='codesnippet',
            index=models.Index(fields=['student', 'title', 'language'], name='codeide_cod_student_717cda_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['student', 'parent'], name='codeide_fol_student_92577b_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('student', 'parent', 'name'), name='uniq_folder_per_parent_per_student'),
        ),
    ]
