# Generated by Django 5.2.5 on 2026-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeide', '0007_folder_codefile_folder_codesnippet_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='file_name',
            field=models.CharField(blank=True, default='', help_text="Individual filename within the project (e.g. 'index.html', 'style.css').", max_length=255),
        ),
    ]
