# Generated by Django 5.2.5 on 2026-05-10 15:04

import codeide.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def clear_codecomments(apps, schema_editor):
    """Delete all existing CodeComment rows so the new FK doesn't violate constraints."""
    CodeComment = apps.get_model('codeide', 'CodeComment')
    CodeComment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_alter_studentprofile_admission_no'),
        ('codeide', '0008_add_file_name_to_submission'),
        ('learning', '0025_course_parent_course'),
    ]

    operations = [
        # Step 0: Clear existing comments before dropping the old FK
        migrations.RunPython(clear_codecomments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='codecomment',
            name='submission',
        ),
        migrations.CreateModel(
            name='CodeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('revised', 'Revised')], default='submitted', max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_projects', to='academics.teacherprofile')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_projects', to='learning.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_projects', to='academics.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='codecomment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='codeide.codeproject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(help_text="Relative path within the project, e.g. 'logins/login.html'", max_length=512)),
                ('language', models.CharField(choices=[('javascript', 'javascript'), ('python', 'python'), ('html', 'html'), ('css', 'css'), ('java', 'java'), ('cpp', 'cpp'), ('other', 'other')], default='html', max_length=64)),
                ('code_text', models.TextField(blank=True, default='')),
                ('is_binary', models.BooleanField(default=False)),
                ('binary_file', models.FileField(blank=True, max_length=512, null=True, upload_to=codeide.models.projectfile_upload_to)),
                ('content_type', models.CharField(blank=True, default='', max_length=127)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('correction_code', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='codeide.codeproject')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.DeleteModel(
            name='CodeSubmission',
        ),
        migrations.AddIndex(
            model_name='codeproject',
            index=models.Index(fields=['lesson', 'student'], name='codeide_cod_lesson__23c6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='codeproject',
            index=models.Index(fields=['student', 'status'], name='codeide_cod_student_33a4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['project', 'language'], name='codeide_pro_project_8e50bd_idx'),
        ),
    ]
