"""
Django management command: import_police_secondary_school_akure

Place this file at:
  <any_app>/management/commands/import_police_secondary_school_akure.py

Make sure management/ and management/commands/ both contain an __init__.py.

Usage:
  python manage.py import_police_secondary_school_akure /path/to/file.xlsx --org-id <PK>

  Optional flags:
    --org-id   Organization PK  (required — no default)
    --plan-id  SubscriptionPlan PK (default: 2)
    --dry-run  Parse without writing to DB

What it creates for each of the 894 students across 29 sheets:
  • Classroom          – named after the sheet tab (created if it doesn't exist)
  • User               – email  = <sanitised-name>pss@techxagonacademy.com
                         username auto-generated by UserManager
                         password = Techxagon@2026
                         is_generated = True
                         primary_org  = the supplied Organization
  • OrganizationMembership (role=student)
  • StudentProfile     (org + classroom linked; admission_no auto-generated by model)
  • UserAccountSubscription (plan pk=2, active, start=today, end=today+90 days)

Notes
-----
- No gender column in this file — gender is simply not set.
- Email collisions within the file AND against existing DB rows are resolved
  by appending a numeric suffix: johndoepss2@techxagonacademy.com
- Everything runs inside a single transaction.atomic(); any error rolls back all.
"""

import re
import unicodedata
from datetime import timedelta

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone
from openpyxl import load_workbook

from accounts.models import User
from academics.models import Classroom, StudentProfile
from orgs.models import Organization, OrganizationMembership
from billing.models import SubscriptionPlan, UserAccountSubscription


# ── helpers ───────────────────────────────────────────────────────────────────

def sanitise_for_email(full_name: str) -> str:
    """
    Convert a full name to a lowercase, ASCII-only, punctuation-free string
    suitable for use as an email local-part.

    Examples:
      "Adeosun Rebecca Kehinde" → "adeosunrebeccakehinde"
      "AGBOOLA BOLUWATIFE"      → "agboolabol uwatife" → "agboolabol uwatife"
                                  → "agboolaboluwatife"
    """
    # NFKD normalisation strips combining accents / special Unicode
    nfkd = unicodedata.normalize("NFKD", full_name)
    ascii_only = nfkd.encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]", "", ascii_only.lower())


# ── command ───────────────────────────────────────────────────────────────────

class Command(BaseCommand):
    help = "Import students from the Police Secondary School Akure Excel file"

    def add_arguments(self, parser):
        parser.add_argument(
            "excel_path",
            type=str,
            help="Absolute or relative path to the .xlsx student list",
        )
        parser.add_argument(
            "--org-id",
            type=int,
            required=True,
            help="Primary key of the Organization these students belong to",
        )
        parser.add_argument(
            "--plan-id",
            type=int,
            default=2,
            help="Primary key of the SubscriptionPlan to assign (default: 2)",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Parse and validate without writing anything to the database",
        )

    def handle(self, *args, **options):
        excel_path = options["excel_path"]
        org_id     = options["org_id"]
        plan_id    = options["plan_id"]
        dry_run    = options["dry_run"]

        # ── pre-flight ────────────────────────────────────────────
        try:
            org = Organization.objects.get(pk=org_id)
        except Organization.DoesNotExist:
            raise CommandError(f"Organization pk={org_id} does not exist.")

        try:
            plan = SubscriptionPlan.objects.get(pk=plan_id)
        except SubscriptionPlan.DoesNotExist:
            raise CommandError(f"SubscriptionPlan pk={plan_id} does not exist.")

        try:
            wb = load_workbook(excel_path, read_only=True)
        except Exception as exc:
            raise CommandError(f"Cannot open Excel file: {exc}")

        password = "Techxagon@2026"
        now      = timezone.now()
        end_at   = now + timedelta(days=90)   # 3-month subscription

        # ── parse all sheets ──────────────────────────────────────
        # Row 0  → school name (skip)
        # Row 1  → column headers S/N | NAME (skip)
        # Row 2+ → (serial_number, student_name, ...)
        sheets_data: list[dict] = []

        for sheet_name in wb.sheetnames:
            ws   = wb[sheet_name]
            rows = list(ws.iter_rows(values_only=True))

            students = []
            for row in rows[2:]:           # skip header rows
                if not row or len(row) < 2:
                    continue
                name = str(row[1] or "").strip()
                if not name:
                    continue
                students.append(name)

            if students:
                sheets_data.append({
                    "classroom_name": sheet_name,   # use tab name directly
                    "students": students,
                })

        wb.close()

        total_parsed = sum(len(s["students"]) for s in sheets_data)
        self.stdout.write(
            f"\nParsed {total_parsed} students across {len(sheets_data)} sheets "
            f"(org_id={org_id}, plan_id={plan_id})"
        )

        if dry_run:
            self.stdout.write(self.style.WARNING("\n--dry-run: nothing will be written.\n"))
            for sd in sheets_data:
                self.stdout.write(f"  {sd['classroom_name']}: {len(sd['students'])} students")
            return

        # ── seed email uniqueness pool ────────────────────────────
        # Pre-load existing generated-student emails so we can avoid
        # collisions without extra per-row DB queries.
        existing_emails: set[str] = set(
            User.objects.filter(email__endswith="@techxagonacademy.com")
            .values_list("email", flat=True)
        )
        # Track emails we assign during THIS run (intra-file deduplication)
        assigned_emails: set[str] = set()

        # ── write to DB atomically ────────────────────────────────
        created_users       = 0
        created_profiles    = 0
        created_memberships = 0
        created_subs        = 0
        created_classrooms  = 0
        skipped_existing    = 0

        with transaction.atomic():
            for sd in sheets_data:
                classroom_name = sd["classroom_name"]

                # Get or create Classroom (teachers field stays empty by default)
                classroom, cls_created = Classroom.objects.get_or_create(
                    organization=org,
                    name=classroom_name,
                    defaults={"code": ""},
                )
                if cls_created:
                    created_classrooms += 1

                sheet_created = 0

                for full_name in sd["students"]:

                    # ── build unique email ────────────────────
                    base_local = sanitise_for_email(full_name)
                    if not base_local:
                        base_local = "student"

                    local_part = base_local + "pss"          # pss suffix for this school
                    candidate  = f"{local_part}@techxagonacademy.com"

                    suffix = 0
                    while candidate in existing_emails or candidate in assigned_emails:
                        suffix   += 1
                        candidate = f"{local_part}{suffix}@techxagonacademy.com"

                    email = candidate
                    assigned_emails.add(email)
                    existing_emails.add(email)

                    # ── skip if user already in DB ────────────
                    if User.objects.filter(email=email).exists():
                        skipped_existing += 1
                        continue

                    # ── split name ────────────────────────────
                    parts      = full_name.strip().split()
                    first_name = parts[0] if parts else ""
                    last_name  = " ".join(parts[1:]) if len(parts) > 1 else ""

                    # ── User (username auto-generated by UserManager) ──
                    user = User.objects.create_user(
                        email=email,
                        password=password,
                        first_name=first_name,
                        last_name=last_name,
                        is_generated=True,
                        is_active=True,
                        primary_org=org,        # ← set primary_org
                    )
                    created_users += 1

                    # ── OrganizationMembership ────────────────
                    OrganizationMembership.objects.create(
                        user=user,
                        organization=org,
                        role=OrganizationMembership.Role.STUDENT,
                        is_active=True,
                    )
                    created_memberships += 1

                    # ── StudentProfile ────────────────────────
                    # admission_no is auto-generated by StudentProfile.save()
                    StudentProfile.objects.create(
                        user=user,
                        organization=org,
                        current_classroom=classroom,
                    )
                    created_profiles += 1

                    # ── UserAccountSubscription (3 months) ────
                    UserAccountSubscription.objects.create(
                        organization=org,
                        user=user,
                        plan=plan,
                        status=UserAccountSubscription.Status.ACTIVE,
                        start_at=now,
                        end_at=end_at,
                        amount=plan.price,
                        currency="NGN",
                    )
                    created_subs += 1
                    sheet_created += 1

                self.stdout.write(
                    f"  ✔ {classroom_name}: "
                    f"{sheet_created}/{len(sd['students'])} created"
                )

        # ── summary ───────────────────────────────────────────────
        self.stdout.write(self.style.SUCCESS(
            f"\n{'='*52}\n"
            f"  Classrooms created  : {created_classrooms}\n"
            f"  Users created       : {created_users}\n"
            f"  Memberships created : {created_memberships}\n"
            f"  Profiles created    : {created_profiles}\n"
            f"  Subscriptions       : {created_subs}\n"
            f"  Skipped (existing)  : {skipped_existing}\n"
            f"{'='*52}"
        ))