"""
Django management command: import_st_patrick_college_emene

Place this file at:
  <any_app>/management/commands/import_st_patrick_college_emene.py

Make sure management/ and management/commands/ both contain an __init__.py.

Usage:
  python manage.py import_st_patrick_college_emene /path/to/file.xlsx --org-id <PK>

Optional flags:
  --org-id    Organization PK  (required)
  --plan-id   SubscriptionPlan PK (default: 2)
  --dry-run   Parse without writing to DB

Excel structure (11 sheets):
  Row 0  → "Name" header
  Row 1+ → full student name (single column A)
  Sheet tab name (stripped) = classroom name

  Sheets: JSS 1A, JSS 1B, JSS 1C, JSS 2A, JSS 2B, JSS2C,
          SS1 A, SS 1B, SS 1C, SS 2A, SS 2B  (344 students total)

What it creates per student:
  • Classroom          – sheet tab name stripped (e.g. "JSS 1A", "SS 1B")
  • User               – email = <sanitised-name>spc@techxagonacademy.com
                         username auto-generated by UserManager
                         password = Techxagon@2026
                         is_generated = True
                         primary_org  = supplied Organization
  • OrganizationMembership (role=student)
  • StudentProfile     (org + classroom; admission_no auto-generated by model)
  • UserAccountSubscription (plan pk=2, active, start=today, end=today+90 days)
"""

import re
import unicodedata
from datetime import timedelta

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone
from openpyxl import load_workbook

from accounts.models import User
from academics.models import Classroom, StudentProfile
from orgs.models import Organization, OrganizationMembership
from billing.models import SubscriptionPlan, UserAccountSubscription


# ── helpers ───────────────────────────────────────────────────────────────────

def sanitise_for_email(text: str) -> str:
    """Strip accents, keep only [a-z0-9], lowercase."""
    nfkd = unicodedata.normalize("NFKD", text)
    ascii_only = nfkd.encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]", "", ascii_only.lower())


# ── command ───────────────────────────────────────────────────────────────────

class Command(BaseCommand):
    help = "Import students from the St Patrick College Emene Excel file"

    def add_arguments(self, parser):
        parser.add_argument(
            "excel_path",
            type=str,
            help="Path to the .xlsx student file",
        )
        parser.add_argument(
            "--org-id",
            type=int,
            required=True,
            help="Primary key of the Organization these students belong to",
        )
        parser.add_argument(
            "--plan-id",
            type=int,
            default=2,
            help="Primary key of the SubscriptionPlan (default: 2)",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Parse and validate without writing anything to the database",
        )

    def handle(self, *args, **options):
        excel_path = options["excel_path"]
        org_id     = options["org_id"]
        plan_id    = options["plan_id"]
        dry_run    = options["dry_run"]

        # ── pre-flight ────────────────────────────────────────────
        try:
            org = Organization.objects.get(pk=org_id)
        except Organization.DoesNotExist:
            raise CommandError(f"Organization pk={org_id} does not exist.")

        try:
            plan = SubscriptionPlan.objects.get(pk=plan_id)
        except SubscriptionPlan.DoesNotExist:
            raise CommandError(f"SubscriptionPlan pk={plan_id} does not exist.")

        try:
            wb = load_workbook(excel_path, read_only=True)
        except Exception as exc:
            raise CommandError(f"Cannot open Excel file: {exc}")

        password = "Techxagon@2026"
        now      = timezone.now()
        end_at   = now + timedelta(days=90)  # 3-month subscription

        # ── parse all sheets ──────────────────────────────────────
        # Row 0 = "Name" header → skip
        # Row 1+ = student full name in column A (index 0)
        # Classroom name = sheet tab name stripped
        sheets_data: list[dict] = []

        for sheet_name in wb.sheetnames:
            ws   = wb[sheet_name]
            rows = list(ws.iter_rows(values_only=True))

            classroom_name = sheet_name.strip()
            students: list[str] = []

            for row in rows[1:]:
                if not row or not row[0]:
                    continue
                name = str(row[0]).strip()
                if name:
                    students.append(name)

            if students:
                sheets_data.append({
                    "classroom_name": classroom_name,
                    "students":       students,
                })

        wb.close()

        total_parsed = sum(len(s["students"]) for s in sheets_data)
        self.stdout.write(
            f"\nParsed {total_parsed} students across "
            f"{len(sheets_data)} sheets "
            f"(org_id={org_id}, plan_id={plan_id})"
        )

        if dry_run:
            self.stdout.write(self.style.WARNING("\n--dry-run: nothing will be written.\n"))
            for sd in sheets_data:
                self.stdout.write(
                    f"  {sd['classroom_name']}: {len(sd['students'])} students"
                )
            return

        # ── seed email uniqueness pool ────────────────────────────
        existing_emails: set[str] = set(
            User.objects.filter(email__endswith="@techxagonacademy.com")
            .values_list("email", flat=True)
        )
        assigned_emails: set[str] = set()  # assigned in THIS run

        # ── write to DB atomically ────────────────────────────────
        created_users       = 0
        created_profiles    = 0
        created_memberships = 0
        created_subs        = 0
        created_classrooms  = 0
        skipped_existing    = 0

        classroom_cache: dict[str, Classroom] = {}

        with transaction.atomic():
            for sd in sheets_data:
                classroom_name = sd["classroom_name"]

                # ── get / create Classroom ────────────────────
                if classroom_name not in classroom_cache:
                    classroom, cls_created = Classroom.objects.get_or_create(
                        organization=org,
                        name=classroom_name,
                        defaults={"code": ""},
                    )
                    if cls_created:
                        created_classrooms += 1
                    classroom_cache[classroom_name] = classroom
                else:
                    classroom = classroom_cache[classroom_name]

                sheet_created = 0

                for full_name in sd["students"]:

                    # ── build unique email ────────────────────
                    base_local = sanitise_for_email(full_name)
                    if not base_local:
                        base_local = "student"

                    local_part = base_local + "spc"      # spc = St Patrick College
                    candidate  = f"{local_part}@techxagonacademy.com"

                    suffix_num = 0
                    while candidate in existing_emails or candidate in assigned_emails:
                        suffix_num += 1
                        candidate   = f"{local_part}{suffix_num}@techxagonacademy.com"

                    email = candidate
                    assigned_emails.add(email)
                    existing_emails.add(email)

                    # ── skip if already in DB ─────────────────
                    if User.objects.filter(email=email).exists():
                        skipped_existing += 1
                        continue

                    # ── split name for User fields ────────────
                    # Names are in ALL CAPS "LAST MIDDLE FIRST" order in the file.
                    # We title-case and store as-is: first word → first_name,
                    # remainder → last_name (keeps the full name searchable).
                    parts      = full_name.title().split()
                    first_name = parts[0] if parts else ""
                    last_name  = " ".join(parts[1:]) if len(parts) > 1 else ""

                    # ── User ──────────────────────────────────
                    user = User.objects.create_user(
                        email=email,
                        password=password,
                        first_name=first_name,
                        last_name=last_name,
                        is_generated=True,
                        is_active=True,
                        primary_org=org,
                    )
                    created_users += 1

                    # ── OrganizationMembership ────────────────
                    OrganizationMembership.objects.create(
                        user=user,
                        organization=org,
                        role=OrganizationMembership.Role.STUDENT,
                        is_active=True,
                    )
                    created_memberships += 1

                    # ── StudentProfile ────────────────────────
                    StudentProfile.objects.create(
                        user=user,
                        organization=org,
                        current_classroom=classroom,
                    )
                    created_profiles += 1

                    # ── UserAccountSubscription (3 months) ────
                    UserAccountSubscription.objects.create(
                        organization=org,
                        user=user,
                        plan=plan,
                        status=UserAccountSubscription.Status.ACTIVE,
                        start_at=now,
                        end_at=end_at,
                        amount=plan.price,
                        currency="NGN",
                    )
                    created_subs += 1
                    sheet_created += 1

                self.stdout.write(
                    f"  ✔ {classroom_name}: "
                    f"{sheet_created}/{len(sd['students'])} created"
                )

        # ── summary ───────────────────────────────────────────────
        self.stdout.write(self.style.SUCCESS(
            f"\n{'='*52}\n"
            f"  Classrooms created  : {created_classrooms}\n"
            f"  Users created       : {created_users}\n"
            f"  Memberships created : {created_memberships}\n"
            f"  Profiles created    : {created_profiles}\n"
            f"  Subscriptions       : {created_subs}\n"
            f"  Skipped (existing)  : {skipped_existing}\n"
            f"{'='*52}"
        ))