"""
Django management command: import_students_profile_data

Place this file at:
  <any_app>/management/commands/import_students_profile_data.py

Make sure management/ and management/commands/ both contain an __init__.py.

Usage:
  python manage.py import_students_profile_data /path/to/students_profile_data.xlsx --org-id <PK>

Optional flags:
  --org-id   Organization PK  (required)
  --plan-id  SubscriptionPlan PK (default: 2)
  --email-suffix  Local-part suffix before @ e.g. "spd" → johndoespd@techxagonacademy.com (default: spd)
  --dry-run  Parse without writing to DB

Excel structure (single sheet "Worksheet"):
  Row 0  → headers: LAST NAME | MIDDLE NAME | FIRST NAME | CLASS | DIVISION/ARM
  Row 1+ → student data

What it creates per student:
  • Classroom          – "<CLASS> <DIVISION>" e.g. "JSS 1 A" (created if absent)
  • User               – email built from full name + suffix + @techxagonacademy.com
                         username auto-generated by UserManager
                         password = Techxagon@2026
                         is_generated = True
                         primary_org  = supplied Organization
  • OrganizationMembership (role=student)
  • StudentProfile     (org + classroom; admission_no auto-generated by model)
  • UserAccountSubscription (plan pk=2, active, start=today, end=today+90 days)

Full name order: FIRST MIDDLE LAST  (natural display order)
  e.g. LAST=AABDULMAALIK, MIDDLE=OLAMILEKAN, FIRST=AYODELE
       → full name "Ayodele Olamilekan Aabdulmaalik"
       → email     "ayodoleolamilekan aabdulmaalikspdp@..." (after sanitise)
"""

import re
import unicodedata
from datetime import timedelta

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone
from openpyxl import load_workbook

from accounts.models import User
from academics.models import Classroom, StudentProfile
from orgs.models import Organization, OrganizationMembership
from billing.models import SubscriptionPlan, UserAccountSubscription


# ── helpers ───────────────────────────────────────────────────────────────────

def sanitise_for_email(text: str) -> str:
    """
    Strip accents, keep only [a-z0-9], lowercase.
    "Ayodele Olamilekan Aabdulmaalik" → "ayodoleolamilekan aabdulmaalik"
                                       → "ayodoleolamilek anaabdulmaalik" (no spaces)
    """
    nfkd = unicodedata.normalize("NFKD", text)
    ascii_only = nfkd.encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]", "", ascii_only.lower())


def build_full_name(last: str, middle: str, first: str) -> str:
    """
    Return natural display order: First [Middle] Last, title-cased.
    Middle is omitted if blank/None.
    """
    parts = [p.strip().title() for p in [first, middle, last] if p and str(p).strip()]
    return " ".join(parts)


# ── command ───────────────────────────────────────────────────────────────────

class Command(BaseCommand):
    help = "Import students from the students_profile_data Excel file (single sheet)"

    def add_arguments(self, parser):
        parser.add_argument(
            "excel_path",
            type=str,
            help="Path to the .xlsx student profile data file",
        )
        parser.add_argument(
            "--org-id",
            type=int,
            required=True,
            help="Primary key of the Organization these students belong to",
        )
        parser.add_argument(
            "--plan-id",
            type=int,
            default=2,
            help="Primary key of the SubscriptionPlan (default: 2)",
        )
        parser.add_argument(
            "--email-suffix",
            type=str,
            default="pssigboora",
            help=(
                "Short suffix appended to the sanitised name before @techxagonacademy.com "
                "(default: spd). E.g. 'spd' → johndoespd@techxagonacademy.com"
            ),
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Parse and validate without writing anything to the database",
        )

    def handle(self, *args, **options):
        excel_path    = options["excel_path"]
        org_id        = options["org_id"]
        plan_id       = options["plan_id"]
        email_suffix  = options["email_suffix"].strip().lower()
        dry_run       = options["dry_run"]

        # ── pre-flight ────────────────────────────────────────────
        try:
            org = Organization.objects.get(pk=org_id)
        except Organization.DoesNotExist:
            raise CommandError(f"Organization pk={org_id} does not exist.")

        try:
            plan = SubscriptionPlan.objects.get(pk=plan_id)
        except SubscriptionPlan.DoesNotExist:
            raise CommandError(f"SubscriptionPlan pk={plan_id} does not exist.")

        try:
            wb = load_workbook(excel_path, read_only=True)
        except Exception as exc:
            raise CommandError(f"Cannot open Excel file: {exc}")

        password = "Techxagon@2026"
        now      = timezone.now()
        end_at   = now + timedelta(days=90)  # 3-month subscription

        # ── parse the single worksheet ────────────────────────────
        ws   = wb["Worksheet"]
        rows = list(ws.iter_rows(values_only=True))
        wb.close()

        # Columns: 0=LAST NAME, 1=MIDDLE NAME, 2=FIRST NAME, 3=CLASS, 4=DIVISION
        raw_students = []
        for i, row in enumerate(rows[1:], start=2):   # row index for error messages
            if not row or not row[0] or not str(row[0]).strip():
                continue

            last_name   = str(row[0] or "").strip()
            middle_name = str(row[1] or "").strip()
            first_name  = str(row[2] or "").strip()
            cls_name    = str(row[3] or "").strip()
            division    = str(row[4] or "").strip()

            if not cls_name:
                self.stderr.write(f"  ⚠ Row {i}: missing CLASS – skipped ({last_name})")
                continue

            classroom_name = f"{cls_name} {division}".strip() if division else cls_name
            full_name      = build_full_name(last_name, middle_name, first_name)

            raw_students.append({
                "full_name":      full_name,
                "classroom_name": classroom_name,
            })

        self.stdout.write(
            f"\nParsed {len(raw_students)} students "
            f"(org_id={org_id}, plan_id={plan_id}, suffix='{email_suffix}')"
        )

        if dry_run:
            self.stdout.write(self.style.WARNING("\n--dry-run: nothing will be written.\n"))
            # Show per-classroom breakdown
            counts: dict[str, int] = {}
            for s in raw_students:
                counts[s["classroom_name"]] = counts.get(s["classroom_name"], 0) + 1
            for cls, cnt in sorted(counts.items()):
                self.stdout.write(f"  {cls}: {cnt} students")
            return

        # ── seed email uniqueness pool ────────────────────────────
        existing_emails: set[str] = set(
            User.objects.filter(email__endswith="@techxagonacademy.com")
            .values_list("email", flat=True)
        )
        assigned_emails: set[str] = set()   # emails assigned in THIS run

        # ── write to DB atomically ────────────────────────────────
        created_users       = 0
        created_profiles    = 0
        created_memberships = 0
        created_subs        = 0
        created_classrooms  = 0
        skipped_existing    = 0

        # Cache classrooms created/fetched in this run to avoid repeat queries
        classroom_cache: dict[str, Classroom] = {}

        with transaction.atomic():
            for stu in raw_students:
                full_name      = stu["full_name"]
                classroom_name = stu["classroom_name"]

                # ── get / create Classroom ────────────────────
                if classroom_name not in classroom_cache:
                    classroom, cls_created = Classroom.objects.get_or_create(
                        organization=org,
                        name=classroom_name,
                        defaults={"code": ""},
                    )
                    if cls_created:
                        created_classrooms += 1
                    classroom_cache[classroom_name] = classroom
                else:
                    classroom = classroom_cache[classroom_name]

                # ── build unique email ────────────────────────
                base_local = sanitise_for_email(full_name)
                if not base_local:
                    base_local = "student"

                local_part = base_local + email_suffix
                candidate  = f"{local_part}@techxagonacademy.com"

                suffix_num = 0
                while candidate in existing_emails or candidate in assigned_emails:
                    suffix_num += 1
                    candidate   = f"{local_part}{suffix_num}@techxagonacademy.com"

                email = candidate
                assigned_emails.add(email)
                existing_emails.add(email)

                # ── skip if already in DB ─────────────────────
                if User.objects.filter(email=email).exists():
                    skipped_existing += 1
                    continue

                # ── split display name for User fields ────────
                parts      = full_name.split()
                first      = parts[0] if parts else ""
                last       = " ".join(parts[1:]) if len(parts) > 1 else ""

                # ── User ──────────────────────────────────────
                user = User.objects.create_user(
                    email=email,
                    password=password,
                    first_name=first,
                    last_name=last,
                    is_generated=True,
                    is_active=True,
                    primary_org=org,
                )
                created_users += 1

                # ── OrganizationMembership ────────────────────
                OrganizationMembership.objects.create(
                    user=user,
                    organization=org,
                    role=OrganizationMembership.Role.STUDENT,
                    is_active=True,
                )
                created_memberships += 1

                # ── StudentProfile ────────────────────────────
                StudentProfile.objects.create(
                    user=user,
                    organization=org,
                    current_classroom=classroom,
                )
                created_profiles += 1

                # ── UserAccountSubscription (3 months) ────────
                UserAccountSubscription.objects.create(
                    organization=org,
                    user=user,
                    plan=plan,
                    status=UserAccountSubscription.Status.ACTIVE,
                    start_at=now,
                    end_at=end_at,
                    amount=plan.price,
                    currency="NGN",
                )
                created_subs += 1

        # ── summary ───────────────────────────────────────────────
        self.stdout.write(self.style.SUCCESS(
            f"\n{'='*52}\n"
            f"  Classrooms created  : {created_classrooms}\n"
            f"  Users created       : {created_users}\n"
            f"  Memberships created : {created_memberships}\n"
            f"  Profiles created    : {created_profiles}\n"
            f"  Subscriptions       : {created_subs}\n"
            f"  Skipped (existing)  : {skipped_existing}\n"
            f"{'='*52}"
        ))