# Generated by Django 5.2.5 on 2025-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('paid', 'paid'), ('void', 'void'), ('uncollectible', 'uncollectible'), ('active', 'active')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('cancelled', 'Cancelled'), ('created', 'created')], default='created', max_length=16),
        ),
    ]
