# Generated by Django 5.2.5 on 2025-09-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_subscriptioninvoice_status_and_more'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='organization_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_invoices', to='orgs.organizationmembership'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_period',
            field=models.CharField(default='30', max_length=8),
        ),
    ]
