# Generated by Django 5.2.5 on 2025-09-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscriptioninvoice_organization_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('cancelled', 'Cancelled'), ('inprogress', 'inprogress'), ('created', 'created')], default='created', max_length=16),
        ),
    ]
