# Generated by Django 5.2.5 on 2025-09-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_subscriptionpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
