# Generated by Django 5.2.5 on 2025-09-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_subscriptioninvoice_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=1250, null=True),
        ),
    ]
