# Generated by Django 5.2.5 on 2025-09-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_subscriptionpayment_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
