# Generated by Django 5.2.5 on 2025-09-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_subscriptionpayment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
