# Generated by Django 5.2.5 on 2025-10-23 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_subscriptionpayment_transaction_id'),
        ('store', '0002_remove_productimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_payments', to='store.product'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscriptioninvoice'),
        ),
    ]
