# Generated by Django 5.2.5 on 2025-10-23 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_subscriptionpayment_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='product',
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='provider',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack')], default='flutterwave', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscriptioninvoice'),
        ),
    ]
