# Generated by Django 5.2.5 on 2025-10-29 11:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_language_teacherprofile_experience_and_more'),
        ('billing', '0011_complaint_complaintattachment_complaintresponse_and_more'),
        ('live', '0010_privatetutoring_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateTutoringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack')], default='flutterwave', max_length=20)),
                ('reference', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('method', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('cancelled', 'Cancelled'), ('inprogress', 'inprogress'), ('created', 'created')], default='created', max_length=16)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('transaction_id', models.CharField(blank=True, max_length=450, null=True)),
                ('redirect_url', models.URLField(blank=True, max_length=1250, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.parentprofile')),
                ('tutoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live.tutoringbooking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
