# Generated by Django 5.2.5 on 2025-10-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_privatetutoringpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateTutoringPayment',
        ),
    ]
