# Generated by Django 5.2.5 on 2025-12-18 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_delete_privatetutoringpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.organizationsubscription'),
        ),
    ]
