# Generated by Django 5.2.5 on 2025-12-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_subscriptioninvoice_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('tutor', 'tutor'), ('subscription', 'subscription')], default='subscription', max_length=16)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.subscriptioninvoice')),
            ],
        ),
    ]
