# Generated by Django 5.2.5 on 2025-12-18 15:25

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_invoicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='number',
            field=models.CharField(default=billing.models.SubscriptionInvoice.invoice_number, editable=False, max_length=20, unique=True),
        ),
    ]
