# Generated by Django 5.2.5 on 2025-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_subscriptioninvoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetype',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetype',
            name='object_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
