# Generated by Django 5.2.5 on 2025-12-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_invoicetype_object_id_invoicetype_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetype',
            name='invoice_type',
            field=models.CharField(choices=[('tutor', 'tutor'), ('subscription', 'subscription'), ('store', 'store')], default='subscription', max_length=16),
        ),
    ]
