# Generated by Django 5.2.5 on 2025-12-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_invoicetype_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
