# Generated by Django 5.2.5 on 2025-12-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_organizationsubscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('open', 'open'), ('paid', 'paid'), ('void', 'void'), ('uncollectible', 'uncollectible'), ('active', 'active')], default='active', max_length=16),
        ),
    ]
