# Generated by Django 5.2.5 on 2025-12-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_alter_organizationsubscription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetype',
            name='object_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
