# Generated by Django 5.2.5 on 2025-12-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_alter_invoicetype_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetype',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
