# Generated by Django 5.2.5 on 2026-01-09 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_useraccountsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='user_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_invoices', to='billing.useraccountsubscription'),
        ),
    ]
