# Generated by Django 5.2.5 on 2026-01-10 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_parentprofile_user_subscription'),
        ('billing', '0025_subscriptioninvoice_user_subscription'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useraccountsubscription',
            name='billing_use_organiz_233a1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='useraccountsubscription',
            name='billing_use_organiz_fd8443_idx',
        ),
        migrations.AddIndex(
            model_name='useraccountsubscription',
            index=models.Index(fields=['organization', 'user', '-start_at'], name='billing_use_organiz_16d27b_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccountsubscription',
            index=models.Index(fields=['organization', 'user', 'status', '-start_at'], name='billing_use_organiz_55918c_idx'),
        ),
    ]
