# Generated by Django 5.2.5 on 2026-01-14 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_parentprofile_user_subscription'),
        ('billing', '0026_remove_useraccountsubscription_billing_use_organiz_233a1d_idx_and_more'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='provider_event',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='provider_status',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('inprogress', 'inprogress'), ('created', 'created'), ('error', 'error'), ('unknown', 'unknown')], default='created', max_length=16),
        ),
        migrations.AddIndex(
            model_name='useraccountsubscription',
            index=models.Index(fields=['organization', 'user', 'status', 'end_at'], name='billing_use_organiz_843eea_idx'),
        ),
    ]
