# Generated by Django 5.2.5 on 2026-02-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_subscriptionpayment_last_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
