# Generated by Django 5.2.5 on 2025-10-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_productimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack')], default='flutterwave', max_length=20),
        ),
    ]
