# Generated by Django 5.2.5 on 2025-12-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_payment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='texagon/product_images/'),
        ),
    ]
