# Generated by Django 5.2.5 on 2026-06-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productimage_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_digital',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('gadget', 'Gadget'), ('iot_device', 'IoT Device'), ('accessory', 'Accessory'), ('hardware', 'Hardware')], db_index=True, default='laptop', max_length=20),
        ),
        migrations.DeleteModel(
            name='Entitlement',
        ),
    ]
