# Generated by Django 5.2.5 on 2026-06-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_is_digital_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='HTML or bullet points for key features'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Key-value pairs for tech specs'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, help_text='e.g. 1 Year Limited Warranty', max_length=100),
        ),
    ]
