# Generated by Django 5.2.5 on 2026-06-12 13:11

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_brand_product_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('7.50'), help_text='VAT/Tax rate as a percentage (e.g., 7.50 for 7.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('flat_shipping_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat rate shipping cost applied to orders', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configuration',
            },
        ),
    ]
