# Generated by Django 5.2.12 on 2026-03-11 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('colour', models.CharField(default='red', help_text='Tailwind-compatible label: red, orange, blue, purple, green…', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'project categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='One-line tagline shown on cards and the hero.', max_length=200)),
                ('description', models.TextField(help_text='Full project description (supports HTML).')),
                ('excerpt', models.CharField(help_text='Short summary shown on listing cards (~120 chars).', max_length=300)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, help_text='Card thumbnail. If blank the emoji + gradient fallback is used.', null=True, upload_to='projects/thumbnails/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('thumb_emoji', models.CharField(choices=[('🌐', 'Web / Globe'), ('🤖', 'Robotics'), ('📊', 'Data / Chart'), ('🔐', 'Cybersecurity'), ('🎨', 'UI/UX / Design'), ('💻', 'Coding / Laptop'), ('⚙️', 'Engineering / Gear'), ('📱', 'Mobile App'), ('🏗️', 'Hardware / Build'), ('🧩', 'Blocks / Logic')], default='💻', help_text='Emoji shown in card when no thumbnail is uploaded.', max_length=8)),
                ('thumb_gradient', models.CharField(choices=[('red-orange', 'Red → Orange'), ('orange-slate', 'Orange → Slate'), ('slate-red', 'Slate → Red'), ('blue-teal', 'Blue → Teal'), ('purple-pink', 'Purple → Pink'), ('green-teal', 'Green → Teal')], default='red-orange', max_length=20)),
                ('video_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True, verbose_name='Live demo URL')),
                ('repo_url', models.URLField(blank=True, verbose_name='Source code / repo URL')),
                ('student_name', models.CharField(max_length=200)),
                ('student_school', models.CharField(blank=True, max_length=200)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='projects/students/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Pin to the top of the homepage projects strip.')),
                ('completed_at', models.DateField(blank=True, help_text='When the project was finished / showcased.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory')),
                ('student_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_projects', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='projects.projecttag')),
            ],
            options={
                'ordering': ['-is_featured', '-completed_at', '-created_at'],
            },
        ),
    ]
