# GENERATED by composite_model.py
# Combines model classes from multiple apps into one file.
# You may need to adjust imports / resolve name collisions manually.


# --- Imports collected from model files ---

from django.db import models
from django.conf import settings
from core.models import TimeStampedModel, NamedModel
from billing.models import OrganizationSubscription, SubscriptionPlan, SubscriptionInvoice
from datetime import timedelta
import time
import secrets
from decimal import Decimal
from django.db import models, transaction
from django.utils import timezone
from django.core.exceptions import ValidationError
from orgs.models import OrganizationMembership, Organization
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db.models import Q
from core.models import TimeStampedModel
from django.core.validators import MinValueValidator
from orgs.models import OrganizationMembership
from live.models import TutoringBooking
from rest_framework import serializers
from orgs.models import Organization
from academics.models import Classroom, StudentProfile
from learning.models import Course


# --- Model classes collected from project ---

class Classroom(NamedModel):
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="classrooms")
    code = models.CharField(max_length=32, blank=True)
    teachers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="teaching_classrooms", blank=True)

    class Meta:
        unique_together = ("organization", "name")



class Subject(NamedModel):
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="subjects")
    code = models.CharField(max_length=32, blank=True)

    class Meta:
        unique_together = ("organization", "name")



class StudentProfile(TimeStampedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="student_profile")
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="students")
    current_classroom = models.ForeignKey(Classroom, on_delete=models.SET_NULL, null=True, blank=True)
    admission_no = models.CharField(max_length=64, blank=True)
    dob = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"Student: {self.user.get_full_name() or self.user.username}"



class Language(models.Model):
    language_name = models.CharField(max_length=225)
    active = models.BooleanField(default=False)



class TeacherProfile(TimeStampedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="teacher_profile")
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="teachers")
    bio = models.TextField(blank=True)
    experience = models.PositiveIntegerField(default=0)
    languages = models.ManyToManyField(Language, blank=True)
    specialties = models.ManyToManyField(Subject, blank=True)

    def __str__(self):
        return f"Teacher: {self.user.get_full_name() or self.user.username} Email: {self.user.email}"



class ParentProfile(TimeStampedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="parent_profile")
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="parents")
    organization_subscription = models.ForeignKey(
        OrganizationSubscription,
        on_delete=models.CASCADE,
        related_name="parent_subs",
        blank=True,
        null=True,
    )
    address = models.TextField(blank=True)

    # use TimeStampedModel.created_at (no new field needed)
    last_billed_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Parent: {self.user.get_full_name() or self.user.username}"

    def _billing_period_days(self):
        """Return billing period in days (int). default to 30 if parsing fails."""
        plan = getattr(self.organization_subscription, "plan", None)
        if not plan:
            return 30
        try:
            return int(plan.billing_period)
        except Exception:
            return 30

    def _invoice_number_for(self, issued_at):
        """Generate a unique invoice number — change format if desired."""
        ts = int(time.time())
        token = secrets.token_hex(4)
        sub_id = self.organization_subscription.id if self.organization_subscription else "none"
        return f"PINV-{sub_id}-{self.id}-{ts}-{token}"

    def generate_subscription_invoices(self, now=None):
        now = now or timezone.now()

        subscription = self.organization_subscription
        if not subscription:
            return []

        if subscription.status != OrganizationSubscription.Status.ACTIVE:
            return []

        plan = subscription.plan
        print(plan, " pppp")
        billing_days = self._billing_period_days()

        if self.last_billed_at:
            next_due = self.last_billed_at + timedelta(days=billing_days)
        else:
            next_due = getattr(self, "created_at", None) or now

        if timezone.is_naive(next_due):
            next_due = timezone.make_aware(next_due)

        created_invoices = []
        max_iterations = 24
        iterations = 0
        
        """
        sub_end_datetime = None
        if subscription.end_date:
            sub_end_datetime = timezone.make_aware(
                datetime.datetime.combine(subscription.end_date, datetime.time.max)
            )

        """
        # Prepare/get parent membership once (we'll attach it to all created invoices)
        # Option: create membership automatically if not present.
        membership, _ = OrganizationMembership.objects.get_or_create(
            user=self.user,
            organization=self.organization,
            role=OrganizationMembership.Role.PARENT,
            defaults={"is_active": True}
        )
        # Note: get_or_create honors the unique_together ("user","organization","role")
        print(iterations, " iterations ",max_iterations)
        while iterations < max_iterations and next_due <= now:
            #if sub_end_datetime and next_due > sub_end_datetime:
                #break

            issued_at = next_due
            amount = Decimal(getattr(plan, "price", 0) or 0)

            inv = SubscriptionInvoice(
                organization_membership=membership,   # attach parent membership
                subscription=subscription,
                number=self._invoice_number_for(issued_at),
                amount=amount,
                currency=getattr(subscription, "currency", "NGN") if hasattr(subscription, "currency") else "NGN",
                issued_at=issued_at,
                due_at=issued_at + timedelta(days=billing_days),
                status=SubscriptionInvoice.Status.ACTIVE,
                meta={"generated_for": "parent_profile", "parent_profile_id": self.id},
            )

            with transaction.atomic():
                inv.save()                    # validation will now accept parent role
                created_invoices.append(inv)
                self.last_billed_at = issued_at
                self.save(update_fields=["last_billed_at"])

            next_due = next_due + timedelta(days=billing_days)
            iterations += 1

        return created_invoices



class ParentChildLink(TimeStampedModel):
    parent = models.ForeignKey(ParentProfile, on_delete=models.CASCADE, related_name="children_links")
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE, related_name="parent_links")
    relationship = models.CharField(max_length=64, blank=True)

    class Meta:
        unique_together = ("parent", "student")



class UserManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)
        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(email, password, **extra_fields)



class User(AbstractUser):
    # remove username column; email becomes the login
    username = None
    email = models.EmailField(unique=True)

    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)
    phone = models.CharField(max_length=32, blank=True)
    primary_org = models.ForeignKey(
        "orgs.Organization",
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name="primary_users",
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []  # no username, so leave empty

    objects = UserManager()



class AdminAccess(models.Model):
    # Only allow staff or superusers to be selectable in forms/admin:
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        limit_choices_to=Q(is_staff=True) | Q(is_superuser=True),
    )
    organizations = models.ManyToManyField("orgs.Organization", blank=True)
    selected_organization = models.ForeignKey("orgs.Organization", 
    related_name="adminaccess_all", on_delete=models.CASCADE, blank=True, null=True)
    active = models.BooleanField(default=True)

    def clean(self):
        # Enforce at the model level (covers shell, scripts, fixtures, etc.)
        if self.user and not (self.user.is_staff or self.user.is_superuser):
            raise ValidationError({
                "user": "AdminAccess can only be granted to staff or superusers."
            })

    def save(self, *args, **kwargs):
        # Ensure clean() runs on every save
        self.full_clean()
        return super().save(*args, **kwargs)



class TeacherProfile(TimeStampedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="teacher_profile")
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="teachers")
    bio = models.TextField(blank=True)
    specialties = models.ManyToManyField(Subject, blank=True)

    def __str__(self):
        return f"Teacher: {self.user.get_full_name() or self.user.username} Email: {self.user.email}"



class SessionToken(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="session_tokens")
    key = models.CharField(max_length=64, unique=True, db_index=True)
    created_at = models.DateTimeField(default=timezone.now)
    expires_at = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    meta = models.JSONField(default=dict, blank=True)

    def __str__(self):
        return f"{self.user_id}:{self.key[:6]}..."

    @classmethod
    def create_for_user(cls, user, hours_valid: int = 24, **meta):
        key = secrets.token_urlsafe(48)[:64]
        now = timezone.now()
        obj = cls.objects.create(
            user=user,
            key=key,
            created_at=now,
            expires_at=now + timedelta(hours=hours_valid),
            is_active=True,
            meta=meta or {},
        )
        return obj

    def revoke(self):
        self.is_active = False
        self.save(update_fields=["is_active"])



class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True



class Test(TimeStampedModel):
    class Visibility(models.TextChoices):
        DRAFT = "draft", "Draft"
        PUBLISHED = "published", "Published"
        CLOSED = "closed", "Closed"

    course = models.ForeignKey("learning.Course", on_delete=models.CASCADE, related_name="tests")
    title = models.CharField(max_length=255)
    duration_minutes = models.PositiveIntegerField(default=30)
    total_marks = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    visibility = models.CharField(max_length=16, choices=Visibility.choices, default=Visibility.DRAFT)
    instructions = models.TextField(blank=True)
    start_at = models.DateTimeField(null=True, blank=True)
    end_at = models.DateTimeField(null=True, blank=True)
    settings = models.JSONField(default=dict, blank=True)

    def __str__(self):
        return self.title



class Question(TimeStampedModel):
    class Type(models.TextChoices):
        SCQ = "scq", "Single Choice"
        MCQ = "mcq", "Multiple Choice"
        TRUE_FALSE = "tf", "True/False"
        SHORT = "short", "Short Answer"
        ESSAY = "essay", "Essay"

    test = models.ForeignKey(Test, on_delete=models.CASCADE, related_name="questions")
    order = models.PositiveIntegerField(default=1)
    qtype = models.CharField(max_length=8, choices=Type.choices)
    body = models.TextField()
    points = models.DecimalField(max_digits=6, decimal_places=2, default=1)
    meta = models.JSONField(default=dict, blank=True)

    class Meta:
        ordering = ["order"]
        unique_together = ("test", "order")



class Choice(TimeStampedModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="choices")
    order = models.PositiveIntegerField(default=1)
    text = models.TextField()
    is_correct = models.BooleanField(default=False)

    class Meta:
        ordering = ["order"]
        unique_together = ("question", "order")



class TestAttempt(TimeStampedModel):
    test = models.ForeignKey(Test, on_delete=models.CASCADE, related_name="attempts")
    student = models.ForeignKey("academics.StudentProfile", on_delete=models.CASCADE, related_name="test_attempts")
    started_at = models.DateTimeField(default=timezone.now)
    submitted_at = models.DateTimeField(null=True, blank=True)
    score = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    answers = models.JSONField(default=dict, blank=True)  # {question_id: ["A", ...] or "True"/"text"}
    status = models.CharField(max_length=16, default="in_progress")  # in_progress, submitted, graded

    class Meta:
        unique_together = ("test", "student", "started_at")



class Assignment(TimeStampedModel):
    course = models.ForeignKey("learning.Course", on_delete=models.CASCADE, related_name="assignments")
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    due_at = models.DateTimeField(null=True, blank=True)
    attachments = models.JSONField(default=list, blank=True)



class Submission(TimeStampedModel):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE, related_name="submissions")
    student = models.ForeignKey("academics.StudentProfile", on_delete=models.CASCADE, related_name="submissions")
    text = models.TextField(blank=True)
    file = models.FileField(upload_to="assignments/submissions/", blank=True, null=True)
    submitted_at = models.DateTimeField(default=timezone.now)
    score = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    feedback = models.TextField(blank=True)

    class Meta:
        unique_together = ("assignment", "student")



class TestAnswer(TimeStampedModel):
    """
    One row per question answered inside a TestAttempt.
    Supports:
      - SCQ/TF: selected_choice
      - MCQ: selected_choice_ids (list of choice ids)
      - SHORT/ESSAY: answer_text
    Also records awarded_points and whether it was auto-graded.
    """
    attempt = models.ForeignKey(TestAttempt, on_delete=models.CASCADE, related_name="answers_rows")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="answers")
    # For SCQ/TF
    selected_choice = models.ForeignKey(Choice, on_delete=models.SET_NULL, null=True, blank=True, related_name="selected_in_answers")
    # For MCQ: store all selected choice IDs (to avoid a join table)
    selected_choice_ids = models.JSONField(default=list, blank=True)
    # For text questions
    answer_text = models.TextField(blank=True)
    # Grading
    awarded_points = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal("0"))
    is_auto_graded = models.BooleanField(default=False)

    class Meta:
        unique_together = ("attempt", "question")
        indexes = [
            models.Index(fields=["attempt"]),
            models.Index(fields=["question"]),
        ]

    def __str__(self):
        return f"Answer attempt={self.attempt_id} q={self.question_id}"



class AttendanceSession(TimeStampedModel):
    course = models.ForeignKey("learning.Course", on_delete=models.CASCADE, related_name="attendance_sessions")
    date = models.DateField()
    topic = models.CharField(max_length=255, blank=True)

    class Meta:
        unique_together = ("course", "date")
        ordering = ["-date"]



class AttendanceRecord(TimeStampedModel):
    session = models.ForeignKey(AttendanceSession, on_delete=models.CASCADE, related_name="records")
    student = models.ForeignKey("academics.StudentProfile", on_delete=models.CASCADE, related_name="attendance_records")
    present = models.BooleanField(default=True)
    note = models.CharField(max_length=255, blank=True)

    class Meta:
        unique_together = ("session", "student")



class SubscriptionPlan(NamedModel):
    price = models.DecimalField(max_digits=12, decimal_places=2, validators=[MinValueValidator(0)])
    billing_period = models.CharField(max_length=8, default="30") # BILLING PERIOD IS CALCULATED IN DAYS. DEFAULT IS 30 DAYS
    features = models.JSONField(default=list, blank=True)
    student_limit = models.PositiveIntegerField(default=0)



class OrganizationSubscription(TimeStampedModel):
    class Status(models.TextChoices):
        ACTIVE = "active", "Active"
        EXPIRED = "expired", "Expired"
        CANCELLED = "cancelled", "Cancelled"
        PAST_DUE = "past_due", "Past Due"

    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="subscriptions")
    plan = models.ForeignKey(SubscriptionPlan, on_delete=models.PROTECT, related_name="subscriptions")
    start_date = models.DateField()
    end_date = models.DateField()
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.ACTIVE)
    auto_renew = models.BooleanField(default=True)
    payment_method = models.CharField(max_length=64, blank=True)
    meta = models.JSONField(default=dict, blank=True)



class SubscriptionInvoice(TimeStampedModel):
    class Status(models.TextChoices):
        OPEN = "open", "open"
        PAID = "paid", "paid"
        VOID = "void", "void"
        UNCOLLECTIBLE = "uncollectible", "uncollectible"
        ACTIVE = "active", "active"
    organization_membership = models.ForeignKey(OrganizationMembership, on_delete=models.CASCADE, related_name="my_invoices", blank=True, null=True)
    subscription = models.ForeignKey(OrganizationSubscription, on_delete=models.CASCADE, related_name="invoices")
    number = models.CharField(max_length=64, unique=True)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=8, default="NGN")
    issued_at = models.DateTimeField(default=timezone.now)
    due_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.ACTIVE)  # open, paid, void, 
    meta = models.JSONField(default=dict, blank=True)
    transaction_id = models.CharField(max_length=450, blank=True, null=True)

    def clean(self):
        super().clean()
        membership = self.organization_membership
        # Allow invoices attached to either teachers or parents
        allowed_roles = {
            OrganizationMembership.Role.PARENT,
        }
        if membership and membership.role not in allowed_roles:
            raise ValidationError({
                'organization_membership': 'organization_membership must be a Teacher or a Parent.'
            })

    def save(self, *args, **kwargs):
        # ensure full_clean runs before saving (so DB never gets invalid data)
        self.full_clean()
        super().save(*args, **kwargs)



class SubscriptionPayment(TimeStampedModel):
    class Status(models.TextChoices):
        SUCCESS = "success", "success"
        FAILED = "failed", "failed"
        CANCELLED = "cancelled", "Cancelled"
        INPROGRESS = "inprogress", "inprogress"
        CREATED = "created", "created"

    invoice = models.ForeignKey(SubscriptionInvoice, on_delete=models.CASCADE, related_name="payments")
    reference = models.CharField(max_length=128, unique=True)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=8, default="NGN")
    method = models.CharField(max_length=32, blank=True)
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.CREATED)  # success, failed, pending
    paid_at = models.DateTimeField(default=timezone.now)
    meta = models.JSONField(default=dict, blank=True)
    transaction_id = models.CharField(max_length=450, blank=True, null=True)
    redirect_url =  models.URLField(max_length=1250, blank=True, null=True)

    def change_current_trans(self, status):
        self.status = status
        self.paid_at = timezone.now()
        self.save()



class NamedModel(TimeStampedModel):
    name = models.CharField(max_length=255, db_index=True)

    class Meta:
        abstract = True

    def __str__(self) -> str:
        return self.name



class Badge(NamedModel):
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="badges")
    icon = models.ImageField(upload_to="badges/", blank=True, null=True)
    criteria = models.TextField(blank=True)
    rules = models.JSONField(default=dict, blank=True)



class BadgeAward(TimeStampedModel):
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE, related_name="awards")
    student = models.ForeignKey("academics.StudentProfile", on_delete=models.CASCADE, related_name="badge_awards")
    awarded_at = models.DateTimeField(auto_now_add=True)
    reason = models.CharField(max_length=255, blank=True)

    class Meta:
        unique_together = ("badge", "student", "awarded_at")



class PointTransaction(TimeStampedModel):
    student = models.ForeignKey("academics.StudentProfile", on_delete=models.CASCADE, related_name="point_transactions")
    points = models.IntegerField()
    reason = models.CharField(max_length=255, blank=True)
    balance_after = models.IntegerField(default=0)



class Streak(TimeStampedModel):
    student = models.OneToOneField("academics.StudentProfile", on_delete=models.CASCADE, related_name="streak")
    current_days = models.PositiveIntegerField(default=0)
    longest_days = models.PositiveIntegerField(default=0)
    last_activity = models.DateField(null=True, blank=True)



class Course(NamedModel):
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="courses")
    subject = models.ForeignKey("academics.Subject", on_delete=models.PROTECT)
    classroom = models.ForeignKey("academics.Classroom", on_delete=models.PROTECT)
    teacher = models.ForeignKey("academics.TeacherProfile", on_delete=models.PROTECT, related_name="courses")
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.teacher.user.email

    class Meta:
        unique_together = ("organization", "subject", "classroom", "teacher")



class Enrollment(TimeStampedModel):
    class Status(models.TextChoices):
        ACTIVE = "active", "Active"
        COMPLETED = "completed", "Completed"
        DROPPED = "dropped", "Dropped"

    student = models.ForeignKey("academics.StudentProfile", on_delete=models.CASCADE, related_name="enrollments")
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="enrollments")
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.ACTIVE)
    progress_pct = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    class Meta:
        unique_together = ("student", "course")



class ModuleCategory(NamedModel):
    active = models.BooleanField(default=True)



class Module(NamedModel):
    class DifficultyLevel(models.TextChoices):
        BEGINNER = "BEGINNER", "BEGINNER"
        INTERMEDIATE = "INTERMEDIATE", "INTERMEDIATE"
        ADVANCED = "ADVANCED", "ADVANCED"
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="modules")
    order = models.PositiveIntegerField(default=1)
    description = models.TextField(blank=True, null=True)
    difficulty = models.CharField(max_length=25, choices=DifficultyLevel.choices, default=DifficultyLevel.BEGINNER)
    category = models.ForeignKey(ModuleCategory, on_delete=models.CASCADE,  blank=True, null=True)
    estimated_duration_in_minutes = models.PositiveIntegerField(blank=True, null=True) 
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["order"]
        unique_together = ("course", "order")



class Lesson(NamedModel):
    class ContentType(models.TextChoices):
        VIDEO = "video", "Video"
        AUDIO = "audio", "Audio"
        PDF = "pdf", "PDF"
        DOC = "doc", "Document"
        LINK = "link", "External Link"

    module = models.ForeignKey(Module, on_delete=models.CASCADE, related_name="lessons")
    cover_image = models.ImageField(upload_to="covers/", blank=True, null=True)
    order = models.PositiveIntegerField(default=1)
    content_type = models.CharField(max_length=16, choices=ContentType.choices)
    file = models.FileField(upload_to="lessons/files/", blank=True, null=True)
    url = models.URLField(blank=True)
    duration_seconds = models.PositiveIntegerField(default=0)
    meta = models.JSONField(default=dict, blank=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["order"]
        unique_together = ("module", "order")



class Material(TimeStampedModel):
    class Kind(models.TextChoices):
        VIDEO = "video", "Video"
        AUDIO = "audio", "Audio"
        PDF = "pdf", "PDF"
        DOC = "doc", "Document"
        IMAGE = "image", "Image"
        OTHER = "other", "Other"

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="materials")
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="materials")
    title = models.CharField(max_length=255)
    kind = models.CharField(max_length=16, choices=Kind.choices)
    file = models.FileField(upload_to="materials/files/", blank=True, null=True)
    url = models.URLField(blank=True)
    tags = models.JSONField(default=list, blank=True)
    is_public = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title



class Bookmark(TimeStampedModel):
    student = models.ForeignKey("academics.StudentProfile", on_delete=models.CASCADE, related_name="bookmarks")
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name="bookmarks")
    note = models.CharField(max_length=255, blank=True)
    position_seconds = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = ("student", "lesson", "position_seconds")



class Note(TimeStampedModel):
    student = models.ForeignKey("academics.StudentProfile", on_delete=models.CASCADE, related_name="notes")
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name="notes")
    content = models.TextField()
    is_private = models.BooleanField(default=True)



class LiveSession(TimeStampedModel):
    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        CONFIRMED = "started", "Started"
        COMPLETED = "completed", "Completed"
        CANCELLED = "cancelled", "Cancelled"
    course = models.ForeignKey("learning.Course", on_delete=models.CASCADE, related_name="live_sessions")
    title = models.CharField(max_length=255)
    scheduled_at = models.DateTimeField()
    duration_minutes = models.PositiveIntegerField(default=60)
    host = models.ForeignKey("academics.TeacherProfile", on_delete=models.PROTECT, related_name="hosted_live_sessions")
    join_url = models.URLField(blank=True)
    recording_url = models.URLField(blank=True)
    meta = models.JSONField(default=dict, blank=True)
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.PENDING)
    active = models.BooleanField(default=True)



class TutoringBooking(TimeStampedModel):
    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        CONFIRMED = "confirmed", "Confirmed"
        COMPLETED = "completed", "Completed"
        CANCELLED = "cancelled", "Cancelled"

    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="tutoring_bookings")
    teacher = models.ForeignKey("academics.TeacherProfile", on_delete=models.PROTECT, related_name="tutoring_bookings")
    student = models.ForeignKey("academics.StudentProfile", on_delete=models.PROTECT, related_name="tutoring_bookings")
    scheduled_at = models.DateTimeField()
    duration_minutes = models.PositiveIntegerField(default=60)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.PENDING)
    notes = models.TextField(blank=True)



class Notification(TimeStampedModel):
    class Kind(models.TextChoices):
        SYSTEM = "system", "System"
        COURSE = "course", "Course"
        PAYMENT = "payment", "Payment"
        ALERT = "alert", "Alert"

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="notifications")
    kind = models.CharField(max_length=16, choices=Kind.choices, default=Kind.SYSTEM)
    title = models.CharField(max_length=255)
    body = models.TextField()
    is_read = models.BooleanField(default=False)
    read_at = models.DateTimeField(null=True, blank=True)
    data = models.JSONField(default=dict, blank=True)

    class Meta:
        indexes = [models.Index(fields=["user", "is_read", "created_at"])]



class Organization(NamedModel):
    slug = models.SlugField(unique=True)
    logo = models.ImageField(upload_to="org_logos/", blank=True, null=True)
    address = models.TextField(blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)
    contact_email = models.EmailField(blank=True)
    contact_phone = models.CharField(max_length=32, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        indexes = [models.Index(fields=["slug"])]

    @property
    def active_subscription(self):
        return self.subscriptions.filter(status="active").order_by("-end_date").first()



class OrganizationMembership(TimeStampedModel):
    class Role(models.TextChoices):
        OWNER = "owner", "Owner"
        ADMIN = "admin", "Admin"
        TEACHER = "teacher", "Teacher"
        STUDENT = "student", "Student"
        PARENT = "parent", "Parent"
        STAFF = "staff", "Staff"

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="memberships")
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name="memberships")
    role = models.CharField(max_length=16, choices=Role.choices)
    is_active = models.BooleanField(default=True)

    class Meta:
        unique_together = ("user", "organization", "role")
        indexes = [models.Index(fields=["organization", "role"])]

    def __str__(self):
        return f"{self.user} @ {self.organization} ({self.role})"



class AcademicSession(NamedModel):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name="sessions")
    start_date = models.DateField()
    end_date = models.DateField()
    is_current = models.BooleanField(default=False)

    class Meta:
        unique_together = ("organization", "name")
        ordering = ["-start_date"]



class ProductCategory(NamedModel):
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="product_categories")
    parent = models.ForeignKey("self", on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        unique_together = ("organization", "name")



class Product(TimeStampedModel):
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="products")
    category = models.ForeignKey(ProductCategory, on_delete=models.SET_NULL, null=True, blank=True)
    sku = models.CharField(max_length=64, unique=True)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=2, validators=[MinValueValidator(0)])
    sale_price = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    stock_qty = models.PositiveIntegerField(default=0)
    is_digital = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    cover_image = models.ImageField(upload_to="store/products/", blank=True, null=True)
    metadata = models.JSONField(default=dict, blank=True)

    def __str__(self):
        return f"{self.sku} — {self.title}"



class Order(TimeStampedModel):
    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        PAID = "paid", "Paid"
        FULFILLED = "fulfilled", "Fulfilled"
        CANCELLED = "cancelled", "Cancelled"
        REFUNDED = "refunded", "Refunded"

    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="orders")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="orders")
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.PENDING)
    subtotal = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    discount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    tax = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    currency = models.CharField(max_length=8, default="NGN")
    paid_at = models.DateTimeField(null=True, blank=True)
    notes = models.TextField(blank=True)

    @property
    def is_paid(self) -> bool:
        return self.status in {self.Status.PAID, self.Status.FULFILLED, self.Status.REFUNDED}



class OrderItem(TimeStampedModel):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name="order_items")
    quantity = models.PositiveIntegerField(default=1)
    unit_price = models.DecimalField(max_digits=12, decimal_places=2)

    class Meta:
        unique_together = ("order", "product")



class Course(NamedModel):
    USAGE_CHOICE = (
        ('public','public'),
        ('private','private'),
    )
    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="courses")
    subject = models.ForeignKey("academics.Subject", on_delete=models.PROTECT)
    classroom = models.ForeignKey("academics.Classroom", on_delete=models.PROTECT)
    teacher = models.ForeignKey("academics.TeacherProfile", on_delete=models.PROTECT, related_name="courses")
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)
    usage_type = models.CharField(
        max_length=20,
        choices=USAGE_CHOICE,
        default='public',
    )
    private_tutor = models.ForeignKey(TutoringBooking, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.teacher.user.email

    class Meta:
        unique_together = ("organization", "subject", "classroom", "teacher")



class PrivateTutoring(TimeStampedModel):
    teacher = models.ForeignKey("academics.TeacherProfile", on_delete=models.PROTECT, related_name="private_tutoring")
    rate_per_hour = models.DecimalField(max_digits=10, decimal_places=2)
    tutoring_duration_days = models.PositiveIntegerField(default=24)
    notes = models.CharField(max_length=225)



class AvailableDay(models.Model):
    class Day(models.TextChoices):
        MONDAY = "monday", "Monday"
        TUESDAY = "tuesday", "Tuesday"
        WEDNESDAY = "wednesday", "Wednesday"
        THURSDAY = "thursday", "Thursday"
        FRIDAY = "friday", "Friday"
        SATURDAY = "saturday", "Saturday"
        SUNDAY = "sunday", "Sunday"

    status = models.CharField(max_length=16, choices=Status.choices)
    private_tutoring = models.ForeignKey(PrivateTutoring, on_delete=models.PROTECT, related_name="available_days")



class TutoringBooking(TimeStampedModel):
    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        CONFIRMED = "confirmed", "Confirmed"
        COMPLETED = "completed", "Completed"
        CANCELLED = "cancelled", "Cancelled"

    organization = models.ForeignKey("orgs.Organization", on_delete=models.CASCADE, related_name="tutoring_bookings")
    teacher = models.ForeignKey("academics.TeacherProfile", on_delete=models.PROTECT, related_name="tutoring_bookings")
    student = models.ForeignKey("academics.StudentProfile", on_delete=models.PROTECT, related_name="tutoring_bookings")
    duration_hours = models.PositiveIntegerField(default=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.PENDING)
    notes = models.TextField(blank=True)



class PrivateTutoring(TimeStampedModel):
    teacher = models.ForeignKey("academics.TeacherProfile", on_delete=models.PROTECT, related_name="private_tutoring")
    course = models.ForeignKey("learning.Course", on_delete=models.PROTECT, related_name="private_tutoring")
    rate_per_hour = models.DecimalField(max_digits=10, decimal_places=2)
    tutoring_duration_days = models.PositiveIntegerField(default=24)
    notes = models.CharField(max_length=225)



class AvailableDay(models.Model):
    class Day(models.TextChoices):
        MONDAY = "monday", "Monday"
        TUESDAY = "tuesday", "Tuesday"
        WEDNESDAY = "wednesday", "Wednesday"
        THURSDAY = "thursday", "Thursday"
        FRIDAY = "friday", "Friday"
        SATURDAY = "saturday", "Saturday"
        SUNDAY = "sunday", "Sunday"

    day = models.CharField(max_length=16, choices=Day.choices)
    private_tutoring = models.ForeignKey(PrivateTutoring, on_delete=models.PROTECT, related_name="available_days")



class PrivateTutoring(TimeStampedModel):
    teacher = models.ForeignKey("academics.TeacherProfile", on_delete=models.PROTECT, related_name="private_tutoring")
    course = models.ForeignKey("learning.Course", on_delete=models.PROTECT, related_name="private_tutoring")
    rate_per_hour = models.DecimalField(max_digits=10, decimal_places=2)
    tutoring_duration_days = models.PositiveIntegerField(default=24) # NUMBER OF DAYS THE TUTORING WILL LAST
    notes = models.CharField(max_length=225)



class TutoringBooking(TimeStampedModel):
    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        CONFIRMED = "confirmed", "Confirmed"
        COMPLETED = "completed", "Completed"
        CANCELLED = "cancelled", "Cancelled"
    private_tutoring = models.ForeignKey(PrivateTutoring, on_delete=models.CASCADE, related_name="tutoring_bookings",
    blank=True, null=True)
    teacher = models.ForeignKey("academics.TeacherProfile", on_delete=models.PROTECT, related_name="tutoring_bookings")
    student = models.ForeignKey("academics.StudentProfile", on_delete=models.PROTECT, related_name="tutoring_bookings")
    duration_hours = models.PositiveIntegerField(default=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.PENDING)
    notes = models.TextField(blank=True)



class ClassroomListSerializer(ClassroomBaseSerializer):
    students = serializers.IntegerField(source="students_count", read_only=True)
    teachers = serializers.IntegerField(source="teachers_count", read_only=True)
    courses  = serializers.IntegerField(source="courses_count", read_only=True)

    class Meta(ClassroomBaseSerializer.Meta):
        fields = ClassroomBaseSerializer.Meta.fields + ["students", "teachers", "courses"]



class StudentMiniSerializer(serializers.ModelSerializer):
    full_name = serializers.SerializerMethodField()

    class Meta:
        model = StudentProfile
        fields = ["id", "admission_no", "full_name"]

    def get_full_name(self, obj):
        u = obj.user
        return (getattr(u, "get_full_name", lambda: "")() or u.email or u.pk)
