# Generated by Django 5.2.5 on 2025-08-27 08:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_choice_ids', models.JSONField(blank=True, default=list)),
                ('answer_text', models.TextField(blank=True)),
                ('awarded_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('is_auto_graded', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_rows', to='assessments.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_answers', to='assessments.choice')),
            ],
            options={
                'indexes': [models.Index(fields=['attempt'], name='assessments_attempt_2bfad7_idx'), models.Index(fields=['question'], name='assessments_questio_905551_idx')],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
