# Generated by Django 5.2.5 on 2026-01-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_testanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], db_index=True, default='online', max_length=16),
        ),
    ]
