# Generated by Django 5.2.5 on 2026-02-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_classroom_unique_together'),
        ('assessments', '0003_test_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, to='academics.studentprofile'),
        ),
    ]
