# Generated by Django 5.2.5 on 2026-02-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_test_excluded_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='require_browser_code',
            field=models.BooleanField(default=False),
        ),
    ]
