# Generated by Django 5.2.5 on 2026-02-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_test_require_browser_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='require_browser_code',
            field=models.BooleanField(default=True),
        ),
    ]
