# Generated by Django 5.2.5 on 2026-05-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_alter_studentprofile_admission_no'),
        ('assessments', '0006_alter_test_require_browser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='client_submission_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('client_submission_id__isnull', False)), fields=('student', 'client_submission_id'), name='uniq_student_client_submission_id'),
        ),
    ]
