# Generated by Django 5.2.5 on 2026-05-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_assignment_lesson_submission_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='answers',
        ),
    ]
