# Generated by Django 5.2.5 on 2026-05-26 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_remove_testattempt_answers'),
        ('orgs', '0003_add_video_conferencing'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='orgs.academicsession'),
        ),
        migrations.AddField(
            model_name='test',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='orgs.academicsession'),
        ),
    ]
