# Generated by Django 5.2.5 on 2026-06-09 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_assignment_academic_session_test_academic_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='show_score',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='HistoricalTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_title', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.CharField(blank=True, max_length=255)),
                ('original_attempt_id', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
