# Generated by Django 5.2.5 on 2025-11-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_language_teacherprofile_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='academics.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'device_id'], name='core_studen_student_ea268e_idx')],
            },
        ),
    ]
