# Generated by Django 5.2.5 on 2025-12-16 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('threshold_xp', models.PositiveIntegerField(help_text='Minimum XP required to be in this tier.', unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Optional explicit ordering if you ever want it independent of threshold.')),
            ],
            options={
                'ordering': ['threshold_xp'],
            },
        ),
    ]
