# Generated by Django 5.2.5 on 2026-02-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='year',
            field=models.CharField(default='2026'),
        ),
    ]
