# Generated by Django 5.2.5 on 2026-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_organization_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='video_conferencing',
            field=models.CharField(choices=[('konnect', 'Konnect'), ('live', 'Live (Legacy)')], default='konnect', help_text='Video conferencing provider used by this organisation.', max_length=16),
        ),
    ]
