# Generated by Django 5.2.5 on 2026-06-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_add_video_conferencing'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_unsubscribed_users',
            field=models.BooleanField(default=False),
        ),
    ]
