# Generated by Django 5.2.5 on 2026-07-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_organization_allow_unsubscribed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_public_cert_request',
            field=models.BooleanField(default=False, help_text='When enabled, this organisation appears in the public certificate request form.'),
        ),
    ]
