# Generated by Django 5.2.5 on 2025-10-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminaccess'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccess',
            name='selected_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminaccess_all', to='orgs.organization'),
        ),
    ]
