# Generated by Django 5.2.5 on 2026-01-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccess',
            name='super_user',
            field=models.BooleanField(default=False),
        ),
    ]
