# Generated by Django 5.2.5 on 2026-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_adminaccess_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
