# Generated by Django 5.2.12 on 2026-03-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(choices=[('robotics', 'Robotics & AI Tutor')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('state_residence', models.CharField(blank=True, max_length=60)),
                ('state_origin', models.CharField(blank=True, max_length=60)),
                ('nationality', models.CharField(blank=True, max_length=60)),
                ('identification', models.CharField(blank=True, max_length=20)),
                ('id_upload', models.FileField(blank=True, null=True, upload_to='applications/ids/')),
                ('education_level', models.CharField(blank=True, max_length=20)),
                ('course_of_study', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('nysc_status', models.CharField(blank=True, max_length=20)),
                ('degree_fields', models.JSONField(blank=True, default=list)),
                ('other_degree', models.CharField(blank=True, max_length=255)),
                ('cv_upload', models.FileField(blank=True, null=True, upload_to='applications/cvs/')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('years_experience', models.CharField(blank=True, max_length=10)),
                ('has_taught', models.CharField(blank=True, max_length=5)),
                ('teaching_location', models.CharField(blank=True, max_length=255)),
                ('has_laptop', models.CharField(blank=True, max_length=5)),
                ('has_internet', models.CharField(blank=True, max_length=5)),
                ('attend_training', models.CharField(blank=True, max_length=5)),
                ('willing_to_relocate', models.CharField(blank=True, max_length=5)),
                ('work_fulltime', models.CharField(blank=True, max_length=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('preferred_states', models.JSONField(blank=True, default=list)),
                ('why_techxagon', models.TextField(blank=True)),
                ('why_select', models.TextField(blank=True)),
                ('future_robotics', models.TextField(blank=True)),
                ('service_agreement', models.CharField(blank=True, max_length=5)),
                ('video_upload', models.FileField(blank=True, null=True, upload_to='applications/videos/')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'position')},
            },
        ),
    ]
