# Generated by Django 5.2.5 on 2026-03-18 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefrontend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsDashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_dashboard', models.BooleanField(default=True)),
                ('can_export_csv', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applications_dashboard_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applications Dashboard Access',
                'verbose_name_plural': 'Applications Dashboard Access',
            },
        ),
    ]
