# Generated by Django 5.2.5 on 2026-03-01 21:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0025_course_parent_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KonnectRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('room_id', models.CharField(max_length=255)),
                ('welcome_message', models.CharField(max_length=1200)),
                ('message', models.CharField(max_length=1200)),
                ('room_url', models.URLField(blank=True, max_length=1200, null=True, unique=True)),
                ('status', models.CharField(choices=[('closed', 'closed'), ('disabled', 'disabled'), ('open', 'open')], default='closed', max_length=16)),
                ('allowed_courses', models.ManyToManyField(blank=True, to='learning.course')),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konnect_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KonnectRoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('konnect_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konnect_users', to='konnect.konnectroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konnect_room_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
