# Generated by Django 5.2.5 on 2026-03-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konnectroom',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
