# Generated by Django 5.2.5 on 2025-08-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_livesession_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
