# Generated by Django 5.2.5 on 2025-09-09 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_livesession_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='thumbnail',
        ),
    ]
