# Generated by Django 5.2.5 on 2025-09-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_remove_livesession_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
