# Generated by Django 5.2.5 on 2025-10-02 22:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_language_teacherprofile_experience_and_more'),
        ('learning', '0008_course_private_tutor_course_usage_type'),
        ('live', '0005_livesession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringbooking',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='tutoringbooking',
            name='scheduled_at',
        ),
        migrations.AddField(
            model_name='tutoringbooking',
            name='duration_hours',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='PrivateTutoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tutoring_duration_days', models.PositiveIntegerField(default=24)),
                ('notes', models.CharField(max_length=225)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_tutoring', to='learning.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_tutoring', to='academics.teacherprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvailableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=16)),
                ('private_tutoring', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='available_days', to='live.privatetutoring')),
            ],
        ),
    ]
