# Generated by Django 5.2.5 on 2025-10-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_remove_tutoringbooking_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringbooking',
            name='organization',
        ),
        migrations.AddField(
            model_name='tutoringbooking',
            name='private_tutoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_bookings', to='live.privatetutoring'),
        ),
    ]
