# Generated by Django 5.2.5 on 2025-10-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_remove_tutoringbooking_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringbooking',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
