# Generated by Django 5.2.5 on 2025-10-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0008_tutoringbooking_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatetutoring',
            name='title',
            field=models.CharField(default='My Private Tutoring', max_length=250),
        ),
    ]
