# Generated by Django 5.2.5 on 2025-10-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0009_privatetutoring_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatetutoring',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
