# Generated by Django 5.2.5 on 2025-12-18 21:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_studentprofile_organization'),
        ('live', '0010_privatetutoring_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateTutoringRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=2500)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.parentprofile')),
                ('tutoring_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='live.tutoringbooking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
