# Generated by Django 5.2.5 on 2026-05-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0011_privatetutoringrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatetutoring',
            name='hours_per_day',
            field=models.FloatField(default=2.0),
        ),
    ]
