# Generated by Django 5.2.5 on 2026-08-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0013_tutoringbooking_session_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='session_type',
            field=models.CharField(choices=[('default', 'Group Call (SFU)'), ('livestream', 'Live Class (Broadcast)')], default='default', max_length=16),
        ),
    ]
