# Generated by Django 5.2.5 on 2026-08-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_alter_lesson_cover_image_alter_lesson_file_and_more'),
        ('live', '0014_livesession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='learning.course'),
        ),
    ]
