# Generated by Django 5.2.5 on 2026-08-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0015_livesession_is_public_alter_livesession_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='is_room_open',
            field=models.BooleanField(default=True),
        ),
    ]
