# Generated by Django 5.2.5 on 2026-08-15 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0016_livesession_is_room_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSessionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_recordings', models.BooleanField(default=False, help_text='If enabled, recordings will be fetched and displayed on student/teacher portals.')),
            ],
            options={
                'verbose_name': 'Live Session Configuration',
                'verbose_name_plural': 'Live Session Configuration',
            },
        ),
    ]
