# Generated by Django 5.2.5 on 2026-06-04 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=20)),
                ('build_number', models.IntegerField()),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('android', 'Android'), ('ios', 'iOS'), ('macos', 'macOS')], max_length=20)),
                ('download_url', models.URLField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('release_notes', models.TextField(blank=True)),
                ('is_force_update', models.BooleanField(default=False)),
                ('min_supported_version', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('version', 'platform')},
            },
        ),
    ]
