# Generated by Django 5.2.5 on 2025-08-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
