# Generated by Django 5.2.5 on 2025-08-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lesson_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
