# Generated by Django 5.2.5 on 2025-08-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_material_active_module_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='material',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
