# Generated by Django 5.2.5 on 2025-09-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_modulecategory_remove_lesson_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='estimated_duration_in_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
