# Generated by Django 5.2.5 on 2025-09-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_module_estimated_duration_in_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
