# Generated by Django 5.2.5 on 2025-10-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_lesson_cover_image'),
        ('live', '0005_livesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='private_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='live.tutoringbooking'),
        ),
        migrations.AddField(
            model_name='course',
            name='usage_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=20),
        ),
    ]
