# Generated by Django 5.2.5 on 2025-10-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_course_private_tutor_course_usage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/covers/'),
        ),
    ]
