# Generated by Django 5.2.5 on 2025-10-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_material_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='No title', max_length=100),
        ),
    ]
