# Generated by Django 5.2.5 on 2025-12-12 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.lesson'),
        ),
    ]
