# Generated by Django 5.2.5 on 2025-12-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_material_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='private_tutor',
        ),
    ]
