# Generated by Django 5.2.5 on 2025-12-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_remove_course_private_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='usage_type',
            new_name='course_type',
        ),
    ]
