# Generated by Django 5.2.5 on 2025-12-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_rename_usage_type_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='texagon/covers/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='texagon/lessons/files/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='texagon/materials/covers/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='texagon/materials/files/'),
        ),
    ]
