# Generated by Django 5.2.5 on 2026-01-02 11:17

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_alter_lesson_cover_image_alter_lesson_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='texagon/lessons/files/'),
        ),
    ]
