# Generated by Django 5.2.5 on 2026-01-06 13:27

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_alter_lesson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='texagon/materials/files/'),
        ),
    ]
