# Generated by Django 5.2.5 on 2026-01-07 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_alter_material_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePassCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_cbt', models.PositiveIntegerField(default=10)),
                ('no_of_code_submission', models.PositiveIntegerField(default=10)),
                ('total_pass_mark_cbt', models.PositiveIntegerField(default=500)),
                ('total_pass_mark_code', models.PositiveIntegerField(default=500)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pass_criteria', to='learning.course')),
            ],
        ),
    ]
