# Generated by Django 5.2.5 on 2026-01-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_coursepasscriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
