# Generated by Django 5.2.5 on 2026-01-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_leaderboardseason_and_more'),
        ('learning', '0018_enrollment_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='leaderboard_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_enrollments', to='gamification.leaderboardseason'),
        ),
    ]
