# Generated by Django 5.2.5 on 2026-01-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_enrollment_leaderboard_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='general_activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
