# Generated by Django 5.2.5 on 2026-01-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_course_general_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='general_activation',
            field=models.BooleanField(default=False),
        ),
    ]
