# Generated by Django 5.2.5 on 2026-01-24 15:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_course_general_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='texagon/covers/'),
        ),
    ]
