# Generated by Django 5.2.5 on 2026-02-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_alter_lesson_cover_image_alter_lesson_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='freeze_code_submission',
            field=models.BooleanField(default=False),
        ),
    ]
