# Generated by Django 5.2.5 on 2026-02-06 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_course_freeze_code_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='parent_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course'),
        ),
    ]
