# Generated by Django 5.2.5 on 2026-05-26 21:22

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_alter_course_classroom_optional'),
        ('orgs', '0003_add_video_conferencing'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='orgs.academicsession'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='texagon/covers/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='texagon/lessons/files/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='texagon/materials/files/'),
        ),
    ]
