# Generated by Django 5.2.5 on 2026-06-12 14:30

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_enrollment_academic_session_alter_lesson_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='texagon/covers/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='texagon/lessons/files/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='texagon/materials/files/'),
        ),
    ]
