# Generated by Django 5.2.5 on 2026-07-13 00:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0028_alter_lesson_cover_image_alter_lesson_file_and_more'),
        ('orgs', '0005_organization_allow_public_cert_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentAssessmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Standard 2026 Grade Scale', max_length=255)),
                ('use_cbt', models.BooleanField(default=True)),
                ('use_code', models.BooleanField(default=True)),
                ('use_assignment', models.BooleanField(default=True)),
                ('use_opw', models.BooleanField(default=True)),
                ('cbt_weight', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('code_weight', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('assignment_weight', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('opw_weight', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('grade_a_threshold', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('grade_b_threshold', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('grade_c_threshold', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('grade_d_threshold', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_configs', to='orgs.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assessment_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='learning.enrollmentassessmentconfig'),
        ),
    ]
