# Generated by Django 5.2.5 on 2025-09-14 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('billing', '0003_subscriptioninvoice_organization_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='organization_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_subs', to='billing.organizationsubscription'),
        ),
    ]
