# Generated by Django 5.2.5 on 2025-09-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_parentprofile_organization_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='last_billed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
