# Generated by Django 5.2.5 on 2025-10-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_parentprofile_last_billed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=225)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='academics.language'),
        ),
    ]
