# Generated by Django 5.2.5 on 2025-12-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_language_teacherprofile_experience_and_more'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='orgs.organization'),
        ),
    ]
