# Generated by Django 5.2.5 on 2026-01-05 15:04

import academics.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_studentprofile_organization'),
        ('learning', '0015_alter_lesson_file'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate of Completion', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('verification_token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked')], db_index=True, default='issued', max_length=16)),
                ('acquired_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('download_after_days', models.PositiveSmallIntegerField(default=7)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=academics.models.certificate_pdf_upload_to)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_certificates', to='learning.course')),
                ('enrollment', models.OneToOneField(help_text='One certificate per enrollment.', on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='learning.enrollment')),
                ('issued_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_enrollment_certificates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_certificates', to='orgs.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_certificates', to='academics.studentprofile')),
            ],
            options={
                'ordering': ['-acquired_at'],
                'indexes': [models.Index(fields=['organization', 'course', 'acquired_at'], name='academics_e_organiz_2a533b_idx'), models.Index(fields=['student', 'acquired_at'], name='academics_e_student_e0e8e4_idx'), models.Index(fields=['status', 'acquired_at'], name='academics_e_status_264c9b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('status', 'issued')), models.Q(('revoked_at__isnull', False), ('status', 'revoked')), _connector='OR'), name='enroll_cert_revoked_requires_timestamp')],
            },
        ),
    ]
