# Generated by Django 5.2.5 on 2026-01-05 18:05

import academics.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_enrollmentcertificate'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCertificateSignatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_1_name', models.CharField(blank=True, max_length=255)),
                ('director_1_title', models.CharField(blank=True, default='Director', max_length=255)),
                ('director_1_signature', models.ImageField(blank=True, null=True, upload_to=academics.models.org_cert_signature_upload_to)),
                ('director_2_name', models.CharField(blank=True, max_length=255)),
                ('director_2_title', models.CharField(blank=True, default='Director', max_length=255)),
                ('director_2_signature', models.ImageField(blank=True, null=True, upload_to=academics.models.org_cert_signature_upload_to)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_signatures', to='orgs.organization')),
            ],
        ),
    ]
