# Generated by Django 5.2.5 on 2026-01-09 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_certificateapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollmentCertificateApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('teacher', 'teacher'), ('admin', 'admin')], default='teacher', max_length=25)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.enrollmentcertificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CertificateApproval',
        ),
    ]
