# Generated by Django 5.2.5 on 2026-01-09 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_studentenrollmentcertificateapproval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollmentcertificateapproval',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='academics.enrollmentcertificate'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollmentcertificateapproval',
            constraint=models.UniqueConstraint(fields=('certificate', 'user_type'), name='unique_approval_per_cert_per_role'),
        ),
    ]
