# Generated by Django 5.2.5 on 2026-01-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_studentenrollmentcertificateapproval_certificate_and_more'),
        ('gamification', '0006_leaderboardseason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentcertificate',
            name='leaderboard_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_certificates', to='gamification.leaderboardseason'),
        ),
    ]
