# Generated by Django 5.2.5 on 2026-01-09 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_enrollmentcertificate_leaderboard_season'),
        ('billing', '0025_subscriptioninvoice_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='user_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_subs', to='billing.useraccountsubscription'),
        ),
    ]
