# Generated by Django 5.2.5 on 2026-02-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_parentprofile_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=20),
        ),
    ]
