# Generated by Django 5.2.5 on 2026-02-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_classroom_class_type'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('organization', 'name', 'code')},
        ),
    ]
