# Generated by Django 5.2.5 on 2026-02-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_no',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
