# Generated by Django 5.2.5 on 2026-02-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_studentprofile_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_no',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
