# Generated by Django 5.2.5 on 2026-05-10 22:57

import academics.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_alter_studentprofile_admission_no'),
        ('assessments', '0007_testattempt_auto_submitted_and_more'),
        ('learning', '0025_course_parent_course'),
        ('orgs', '0002_organization_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Teacher notes / description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('recipient_mode', models.CharField(choices=[('selected', 'Selected Students'), ('course', 'All in Course'), ('classroom', 'All in Classroom')], default='selected', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('share_token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reports', to='learning.course')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reports', to='orgs.organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to='academics.teacherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('video_file', models.FileField(blank=True, max_length=512, null=True, upload_to=academics.models.report_video_upload_to)),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, etc.)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academics.teacherreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cbt_scores', models.JSONField(blank=True, default=dict)),
                ('coding_scores', models.JSONField(blank=True, default=dict)),
                ('teacher_remark', models.TextField(blank=True)),
                ('parent_viewed', models.BooleanField(default=False)),
                ('parent_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='academics.studentprofile')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='academics.teacherreport')),
            ],
            options={
                'ordering': ['student__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportCodingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_title', models.CharField(blank=True, max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learning.lesson')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_items', to='academics.teacherreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCBTItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_title', models.CharField(blank=True, max_length=255)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assessments.test')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_items', to='academics.teacherreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='academics.teacherreport')),
            ],
            options={
                'ordering': ['order', 'activity_date'],
            },
        ),
        migrations.AddIndex(
            model_name='teacherreport',
            index=models.Index(fields=['organization', 'teacher', 'status'], name='academics_t_organiz_9e212a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherreport',
            index=models.Index(fields=['course', 'status'], name='academics_t_course__382efe_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrecipient',
            index=models.Index(fields=['student', 'report'], name='academics_r_student_4b196f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportrecipient',
            unique_together={('report', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcodingitem',
            unique_together={('report', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcbtitem',
            unique_together={('report', 'test')},
        ),
    ]
