# Generated by Django 5.2.5 on 2026-05-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_teacherreport_reportvideo_reportrecipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
