# Generated by Django 5.2.5 on 2026-05-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_teacherprofile_has_seen_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
