# Generated by Django 5.2.5 on 2026-05-16 14:25
# Manually fixed: PostgreSQL cannot cast boolean -> jsonb directly.
# Solution: drop the old boolean column and re-add it as jsonb with a default of '{}'.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_parentprofile_has_seen_onboarding'),
    ]

    operations = [
        # ── ParentProfile ────────────────────────────────────────────────────
        migrations.RunSQL(
            sql="""
                ALTER TABLE academics_parentprofile
                    DROP COLUMN has_seen_onboarding;
                ALTER TABLE academics_parentprofile
                    ADD COLUMN has_seen_onboarding jsonb NOT NULL DEFAULT '{}';
            """,
            reverse_sql="""
                ALTER TABLE academics_parentprofile
                    DROP COLUMN has_seen_onboarding;
                ALTER TABLE academics_parentprofile
                    ADD COLUMN has_seen_onboarding boolean NOT NULL DEFAULT false;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='parentprofile',
                    name='has_seen_onboarding',
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
        ),
        # ── TeacherProfile ───────────────────────────────────────────────────
        migrations.RunSQL(
            sql="""
                ALTER TABLE academics_teacherprofile
                    DROP COLUMN has_seen_onboarding;
                ALTER TABLE academics_teacherprofile
                    ADD COLUMN has_seen_onboarding jsonb NOT NULL DEFAULT '{}';
            """,
            reverse_sql="""
                ALTER TABLE academics_teacherprofile
                    DROP COLUMN has_seen_onboarding;
                ALTER TABLE academics_teacherprofile
                    ADD COLUMN has_seen_onboarding boolean NOT NULL DEFAULT false;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='teacherprofile',
                    name='has_seen_onboarding',
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
        ),
    ]
