# Generated by Django 5.2.5 on 2026-05-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_alter_parentprofile_has_seen_onboarding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='has_seen_onboarding',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
