# Generated by Django 5.2.5 on 2026-07-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_manualcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcertificate',
            name='template',
            field=models.CharField(default='techxagon', help_text='Certificate template: techxagon or akure', max_length=32),
        ),
    ]
