# Generated by Django 5.2.5 on 2026-08-04 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_certificaterequest'),
        ('offline_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrecipient',
            name='offline_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ReportOfflineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opw_title', models.CharField(blank=True, max_length=255)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('opw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='offline_work.offlinepracticalwork')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_items', to='academics.teacherreport')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('report', 'opw')},
            },
        ),
    ]
