# Generated by Django 5.2.5 on 2025-10-11 19:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_language_teacherprofile_experience_and_more'),
        ('gamification', '0001_initial'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('first_steps', 'First Steps'), ('code_warrior', 'Code Warrior'), ('quiz_master', 'Quiz Master'), ('streak_champion', 'Streak Champion'), ('course_conqueror', 'Course Conqueror')], max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='star', max_length=64)),
                ('category', models.CharField(default='General', max_length=64)),
                ('target_value', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='icon',
        ),
        migrations.AddField(
            model_name='badge',
            name='color',
            field=models.CharField(default='bg-gray-400', max_length=64),
        ),
        migrations.AddField(
            model_name='badge',
            name='icon_name',
            field=models.CharField(default='medal', max_length=64),
        ),
        migrations.AddField(
            model_name='badge',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='badgeaward',
            unique_together={('badge', 'student')},
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['organization', 'points'], name='gamificatio_organiz_548428_idx'),
        ),
        migrations.AddIndex(
            model_name='badgeaward',
            index=models.Index(fields=['student', 'badge'], name='gamificatio_student_a614d8_idx'),
        ),
        migrations.AddField(
            model_name='achievementdefinition',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievement_defs', to='orgs.organization'),
        ),
    ]
