# Generated by Django 5.2.5 on 2025-10-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_achievementdefinition_alter_badge_options_and_more'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='orgs.organization'),
        ),
    ]
