# Generated by Django 5.2.5 on 2025-12-14 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_studentprofile_organization'),
        ('gamification', '0003_alter_badge_organization'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementAcquired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('value_at_unlock', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('value', models.IntegerField(default=1)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='achievementdefinition',
            name='target_value',
        ),
        migrations.AddField(
            model_name='achievementdefinition',
            name='rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='achievementdefinition',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['student', 'created_at'], name='gamificatio_student_81703a_idx'),
        ),
        migrations.AddConstraint(
            model_name='achievementdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_org_achievement_code'),
        ),
        migrations.AddField(
            model_name='achievementacquired',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquired', to='gamification.achievementdefinition'),
        ),
        migrations.AddField(
            model_name='achievementacquired',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_acquired', to='academics.studentprofile'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='academics.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='achievementacquired',
            index=models.Index(fields=['student', 'definition'], name='gamificatio_student_a03226_idx'),
        ),
        migrations.AddIndex(
            model_name='achievementacquired',
            index=models.Index(fields=['definition', 'acquired_at'], name='gamificatio_definit_2bcbd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='achievementacquired',
            unique_together={('definition', 'student')},
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['organization', 'event_type', 'occurred_at'], name='gamificatio_organiz_54aaa8_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['student', 'event_type', 'occurred_at'], name='gamificatio_student_82009f_idx'),
        ),
    ]
