# Generated by Django 5.2.5 on 2025-12-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_achievementacquired_activityevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
