# Generated by Django 5.2.5 on 2026-01-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_organizationcertificatesignatures'),
        ('gamification', '0005_activityevent_dedupe_key'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='activityevent',
            name='gamificatio_organiz_54aaa8_idx',
        ),
        migrations.RemoveIndex(
            model_name='activityevent',
            name='gamificatio_student_82009f_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointtransaction',
            name='gamificatio_student_81703a_idx',
        ),
        migrations.AddField(
            model_name='leaderboardseason',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_seasons', to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='achievementacquired',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_acquired', to='gamification.leaderboardseason'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='gamification.leaderboardseason'),
        ),
        migrations.AddField(
            model_name='badgeaward',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to='gamification.leaderboardseason'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='gamification.leaderboardseason'),
        ),
        migrations.AddField(
            model_name='streak',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_streaks', to='gamification.leaderboardseason'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['organization', 'season', 'event_type', 'occurred_at'], name='gamificatio_organiz_9f36df_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['student', 'season', 'event_type', 'occurred_at'], name='gamificatio_student_b0f4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['student', 'season', 'created_at'], name='gamificatio_student_00acba_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['season', 'created_at'], name='gamificatio_season__960d69_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardseason',
            index=models.Index(fields=['organization', 'is_active'], name='gamificatio_organiz_8046cf_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardseason',
            index=models.Index(fields=['organization', 'start_at', 'end_at'], name='gamificatio_organiz_58aefe_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardseason',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_org_season_slug'),
        ),
    ]
