# Generated by Django 5.2.5 on 2026-01-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_leaderboardseason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
