# Generated by Django 5.2.5 on 2026-05-11 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_teacherreport_reportvideo_reportrecipient_and_more'),
        ('gamification', '0007_badge_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='academics.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='streak',
            unique_together={('student', 'season')},
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['student', 'season'], name='gamificatio_student_ea23de_idx'),
        ),
    ]
