# Generated by Django 5.2.5 on 2026-05-26 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('orgs', '0003_add_video_conferencing'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='orgs.academicsession'),
        ),
    ]
