# Generated by Django 5.2.5 on 2026-07-08 16:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0029_certificaterequest'),
        ('learning', '0028_alter_lesson_cover_image_alter_lesson_file_and_more'),
        ('orgs', '0005_organization_allow_public_cert_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePracticalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(choices=[('assignment', 'Assignment'), ('assessment', 'Assessment'), ('exam', 'Exam'), ('quiz', 'Quiz'), ('project', 'Project'), ('practical', 'Practical')], db_index=True, default='assignment', max_length=16)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=7)),
                ('conducted_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=16)),
                ('academic_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_practical_works', to='orgs.academicsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_practical_works', to='learning.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_practical_works', to='academics.teacherprofile')),
            ],
            options={
                'verbose_name': 'Off-Practical Work',
                'verbose_name_plural': 'Off-Practical Works',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflinePracticalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_offline_scores', to='academics.teacherprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_practical_scores', to='academics.studentprofile')),
                ('opw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='offline_work.offlinepracticalwork')),
            ],
            options={
                'verbose_name': 'OPW Score',
                'verbose_name_plural': 'OPW Scores',
                'ordering': ['student__user__first_name', 'student__user__last_name'],
                'unique_together': {('opw', 'student')},
            },
        ),
    ]
